name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build Docker Image
        run: docker build -t backend-moviemanagement:$(date+%s) .\Backend.MovieManagement.csproj

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/prog8060